### ISSUE TITLE
Where does the senderId come from?

### ISSUE THREAD

**Issue by eastwood** [alexemanuelol/rustplusplus-credential-application#2]
Hey :) Good work btw!

Just wondering where you sourced the senderId for FCM from?

https://github.com/alexemanuelol/rustPlusPlus-Credential-Application/blob/main/src/App.vue#L176

**Comment by alexemanuelol** [comment]
Hey, did you ever get your question answered? :)

**Comment by eastwood** [comment]
Unfortunately no :( I reached out on discord too and it wasn't made clear to me.

I guess fundamentally, i'm not sure how FCM applications work and didn't want to be sending data somewhere that isn't responsible. Let me know if you find out ;)

**Comment by alexemanuelol** [comment]
It's unlikely Ill dig into it any further, but if I do stumble upon it Ill let you know ;)

**Comment by eastwood** [comment]
You can probably close this story as you've fetched it from https://github.com/liamcottle/rustplus.js/blob/82a0616bead146d272dd2fd89f242d602948e392/cli/index.js#L145 directly.

Perhaps Liam will reply, but yea happy to close for now and leave this comment as reference.
